#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd.
#Your script should only display:username, user id, Home directory path for the user
echo "Enter the directory /etc/passwd: "
read -r PASSWDDIR
START=0
END=1
while [ $START -lt $END ];
do
	cut -d ":" -f 1,3,6 "$PASSWDDIR"
	((START++))
done
