#!/usr/bin/env bash
#a Bash script that gives you information about the school file.
FILE="school"
if [ -a "$FILE" ];
then
	echo "$FILE file exists"
	if [ -s "$FILE" ];
	then
		echo "$FILE file is not empty"
	else
		echo "$FILE file is empty"
	fi
	if [ -f "$FILE" ];
	then
		echo "$FILE is a regular file"
	else
		:
	fi
else
	echo "$FILE file does not exist"
fi
