#!/usr/bin/env bash
# Write a Bash script that displays To infinity and beyond indefinitely.
START=0
END=1

trap 'echo "I am invincible!!!"' SIGTERM

while [ $START -lt $END ];
do
	echo "To infinity and beyond"
	sleep 2
done
